---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: homeserver
      containers:
      - name: main
        image: tmodloader:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: data
          mountPath: /home/tml/.local/share/Terraria/tModLoader
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: main
---
apiVersion: v1
kind: Service
metadata:
  name: main
spec:
  type: NodePort
  ports:
    - port: 7770
      nodePort: 7777
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: main
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
