---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: homeserver
      containers:
      - name: main
        image: tmodloader:latest
        imagePullPolicy: IfNotPresent
        tty: true
        stdin: true
        volumeMounts:
        - name: data
          mountPath: /home/tml/.local/share/Terraria/tModLoader
        - name: dockerenv
          mountPath: /.dockerenv
          subPath: dockerenv
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: main
        - name: dockerenv
          configMap:
            name: dockerenv
---
apiVersion: v1
kind: Service
metadata:
  name: main
spec:
  type: NodePort
  ports:
    - port: 7777
      nodePort: 31777
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: main
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
# pass dockerenv checking
apiVersion: v1
kind: ConfigMap
metadata:
  name: dockerenv
data:
  dockerenv: test
---
