[http.serversTransports.ignorecert]
  insecureSkipVerify = true

[http.routers.traefik-dashboard]
    rule = "Host(`router.proxy.rmtt.tech`)"
    entryPoints = ["websecure"]
    service = "api@internal"
    tls = { certResolver = "dnsresolver" }

[http.routers.homeserver-pve]
  rule = "Host(`homeserver.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "homeserver-pve"
  tls = { certResolver = "dnsresolver" }

[http.services.homeserver-pve.loadBalancer]
    passHostHeader = true
    serversTransport = "ignorecert"
    [[http.services.homeserver-pve.loadBalancer.servers]]
        url = "https://homeserver.infra.rmtt.host:8006"


[http.routers.nas]
  rule = "Host(`nas.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "nas"
  tls = { certResolver = "dnsresolver" }

[http.services.nas.loadBalancer]
    passHostHeader = true
    [[http.services.nas.loadBalancer.servers]]
        url = "http://nas.infra.rmtt.host"


[http.routers.pbs]
  rule = "Host(`pbs.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "pbs"
  tls = { certResolver = "dnsresolver" }

[http.services.pbs.loadBalancer]
    passHostHeader = true
    serversTransport = "ignorecert"
    [[http.services.pbs.loadBalancer.servers]]
        url = "https://pbs.infra.rmtt.host:8007"

[http.routers.uptime]
  rule = "Host(`status.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "uptime"
  tls = { certResolver = "dnsresolver" }

[http.services.uptime.loadBalancer]
    passHostHeader = true
    [[http.services.uptime.loadBalancer.servers]]
        url = "http://cn2-box.infra.rmtt.host:8080"


[http.routers.claw]
  rule = "Host(`claw.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "claw"
  tls = { certResolver = "dnsresolver" }

[http.services.claw.loadBalancer]
    passHostHeader = true
    [[http.services.claw.loadBalancer.servers]]
        url = "http://claw.infra.rmtt.host:18080"
