service:
    nodePort: ENC[AES256_GCM,data:BLGA/uM=,iv:gdgYgCMoyW9PpPWghhTOVUHj8SdNYh56qg/hTeVZaAg=,tag:fUVCikl+HEBaWq7d2RyX3w==,type:int]
persistence:
    enabled: ENC[AES256_GCM,data:K44mOA==,iv:V1ocmyO+qJTb9lN3TB/0yWEVp42vxy+XMGBlblfJzqc=,tag:vTo1hBBvU9DOTq0xIE8cRA==,type:bool]
    size: ENC[AES256_GCM,data:2z1IEoQ=,iv:XKDY7m2ED17zTETarmLN9ZwQd02Ag6Lc45RHO9IVc14=,tag:tEN7ieTqSLD+GQi5RYHdRQ==,type:str]
    storageClassName: ENC[AES256_GCM,data:dL2S,iv:WIo1tfghGqZ+4CnnRA7yLZaoZo7Tio+Er0tmLJ8GxLs=,tag:BH4A2pO6nPeLCfjQr6MbZA==,type:str]
    accessModes:
        - ENC[AES256_GCM,data:XfnC7Q3ZG0V7Lb9Cpg==,iv:a+P2ZPnN1omc7K3RnR67Ch82oRGg+26W9ls3DXdk54o=,tag:1diP6nF0yNsxvuULpdCx2A==,type:str]
database:
    size: ENC[AES256_GCM,data:WBoB,iv:7RhecJIn0KmkUCI5MANYOEfIF7r+2phOhhAZyXkmf0c=,tag:F/C486lKe7u2+FCBPHgG/g==,type:str]
    storageClassName: ENC[AES256_GCM,data:2hJyiuiF+obOlw==,iv:xmoPXfnPVxrq6YVxBPYhkWlyL7PSE1WrEBsGFdwFiUA=,tag:JG4h92NJG23ap+yzotBxIw==,type:str]
nodeSelector:
    kubernetes.io/hostname: ENC[AES256_GCM,data:7kDUzoHt/yeSOtg=,iv:imzVPzuGid4LLmHaAuoyaomLPqASdbLUYezztPtxhv0=,tag:9u0+rZhYjic8lIGBCjQ/Qw==,type:str]
secrets:
    n8nEncryptionKey: ENC[AES256_GCM,data:wDUQr2AhFqIgdKB4pcgeyDbIL9zT8EGh7kioEpBRjLs=,iv:A4ANRxoD4OALxzlzfHu4dBNzHZQzUwILnQ7/kfUNPeE=,tag:BhM3yUHQx+wQGTn6oj2dKw==,type:str]
    runnersAuthToken: ENC[AES256_GCM,data:VAK+qmTGN3RfYWL2uimrPCjV5eOtQlUbuD9Rt+1pgQbLDBbxwzrpV26NsZq/b3XWHWSk73p0xKeOC7lrSWOaRQ==,iv:IEXK+WlrxUaKV0k8MKH1f/xcPtUu7tkZqExU35p61GE=,tag:BVZqQd25HBIP5i8BH4FRlA==,type:str]
env:
    - name: ENC[AES256_GCM,data:afQfaMjGbc0=,iv:wmKFreot2sxvgMdLLqfYhmXpaW9iEBieLtRB+C1BnyQ=,tag:waz6+boBcGL+xmTmVrbcPg==,type:str]
      value: ENC[AES256_GCM,data:amG0JRbIG+xetU2JJv9Zwf21,iv:HBQKrmzJtsGEfqXbwIkcH+OAeaMqTHD9IYO4QmBbzm0=,tag:n14IG7FtcR+8GOhhHchjhg==,type:str]
    - name: ENC[AES256_GCM,data:LpP/+kdA79k=,iv:G3MACiT37rM/5yl2Vrw6PJ3Zf+i7U9w2NWuNS62I3CY=,tag:TNr9ZsjRcIP58pUx7g1u9A==,type:str]
      value: ENC[AES256_GCM,data:7qvNPw==,iv:hsOUKsHnfnxbwDBgaMPMJtqsjS08e3VKmjah7vaabJs=,tag:MpCOG0B0BEVGFDckvLIdEw==,type:str]
    - name: ENC[AES256_GCM,data:Fj4HINboGoaAa1IM,iv:S7A3lCy54sGk5WNuwdtQt8/YgOQPqoN2Hmcl/2RHrWA=,tag:Ihj3/KG8YfulstP8NMyygQ==,type:str]
      value: ENC[AES256_GCM,data:EpfKiKY=,iv:t0YAoIWQdrNR2oRiL9qeQkffUw1NyqzD+5xs/DampWA=,tag:T+ybJjET6Q8nLbKb0pk0CQ==,type:str]
    - name: ENC[AES256_GCM,data:DvmvXuhuFUUSWbc=,iv:gtOykAoxy80ncwo9iPT5eJJCxC5bMntHQNoJnHqeek4=,tag:wncjuZxkKXXp3XxKr5h6xw==,type:str]
      value: ENC[AES256_GCM,data:PfuHFI7JmCLSm19vJAWySaIuJberFgz50UZ5,iv:mBcvVaV5gM/ixh1TivtfsAZ3hii+6DQgd0CbIbsYQik=,tag:7oTqzmFsZro1PzcUcp2jQg==,type:str]
    - name: ENC[AES256_GCM,data:59MMK0kDI4f6d5F0hli5TzjN8Q==,iv:4O8jncmOFacfR85ucw+0HTVdN1WrqZqHKFpYIkHgJjc=,tag:czpWgOupEskmCJiw0IydZg==,type:str]
      value: ENC[AES256_GCM,data:61eomPP0jneNaUX0ODIQBJF76XcwAy7FTFT7,iv:3v0MS/kkNNfjiR4Rkht3W5hX2U4mbZr1TNtrbiCE33E=,tag:4OTGumCyoHB2tLoOaIu0Bw==,type:str]
    - name: ENC[AES256_GCM,data:RRLoc2dnqfRKHAdjmwiggd2REP360SJWEE7de4e/Iv/7,iv:yUtY6IojLDNcDgF1fP9kMBIOPOBwADyyHdsTLEjU8VE=,tag:q8USMRd+Ln9c7xrCEYGXuA==,type:str]
      value: ENC[AES256_GCM,data:QPiTzg==,iv:8Sjez+k5hjUzSB3kqJahYs/z0WCwdPOoKgTbX6q8M0E=,tag:2pYeR5pCxWOUFC/ZQUg9GQ==,type:str]
    - name: ENC[AES256_GCM,data:TMW0Xw8OXabj1NIbSX5gQRPSoS2bQxdK/XbPPHA=,iv:umUg2IM4YHly1+BUXBe15Tr4JDQ1SiPC/pTJSEJ79z0=,tag:xF7YnTi7aoplyS10Anihzg==,type:str]
      value: ENC[AES256_GCM,data:hntj,iv:w+v1w2JktgjJpwLc3lnYejmk5rppjW8n+Mqhj9VgBGI=,tag:zS8QEglkhkpljgHzCK1Xdg==,type:str]
    - name: ENC[AES256_GCM,data:bDXmmMewePtHmoZBDUzCrgc/TjlckEcQ,iv:+2pDZLNDhU/fAaYgO3udCCSfDcRjTCMfYiVWi/LrZKs=,tag:rT0NqVc+sKWyPKb5Ctaz4g==,type:str]
      value: ENC[AES256_GCM,data:wI9G/qgZZs9RC5ILPQIR8JkI,iv:2/dLKOf40xcMncPM6n8pyu4isxZVCEHg1qfOFdzOApU=,tag:gf85KO9n4py6JWndmVHNMQ==,type:str]
    - name: ENC[AES256_GCM,data:qa1sACAayD+Qca90e6qPi5kFcxvrwPCJ3KWYdXghqAs=,iv:AWV7I+zXJNUDZFE3393ywU6NkHFfyWYNvCKbzQkAS2c=,tag:3XJODJ0JqP2N55I9ySrJQQ==,type:str]
      value: ENC[AES256_GCM,data:sV8Cfz3N5DcjWpcIZR813Zwip3H2Ik8Ujpkf1qAztRX1UBpdJVvc6yjc2+VZf/LJJU5P3Ts8f13gqQus,iv:aj+lCBxAQQ2DZVB2ezxJUqsIhOByPXzCu47x3DN44Ik=,tag:9hFMyfgEW6Bp8CBdViP2fA==,type:str]
sops:
    lastmodified: "2026-05-23T15:46:39Z"
    mac: ENC[AES256_GCM,data:3ptE6HLC1cvb6xNZdhVWFBeiFJTfZjRufgUFjkNLrEqTTYtNQj0xKH6AlOxflpvNp/LScvwrOE5caZIyTFUwdYzC2AuokYKnBIgURD4Gq6OJFjHWJ1z7j3FdCZJ/Hx5O8mi4qxGfEspNkla31KFKQdFGE2UZ4M7n92Y4HxE9Y1w=,iv:6hQtJqTIUJyXPwqkG+y/t2svy+6esHUj2CwrCCPeb+U=,tag:G+OoPqjaAsouZoeVnJuv4A==,type:str]
    pgp:
        - created_at: "2026-05-23T05:29:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAmBY0MyiNyX86TClEzusOGDm6hQHEEkcv+LHKlB3tqnMw
            GhP2XSsnkbsVgeo/ReVk52dNObriciT28OvY7KsWvMjLT5BZh/oMbJlqcz1biha7
            0lEBseUwniXkeoQlUJQR75LJO5qwleUvmv5+DYvrTwMBoo9RH/Ww4qsgBjOCyM9V
            tCmb7pAzS/QQqjvyGpRPu4HL8RHWKZJ0vTSSPSSsxLXESXk=
            =SWsg
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    unencrypted_suffix: _unencrypted
    version: 3.13.0
