jwt_secret: ENC[AES256_GCM,data:PXw/Hfq60vZvabtA9vCPRY6+wCMeL467pRHPj5VKyzepJlinAF3JqteRJ/KiXCIgKBH5oVDrgP4quO42+CUK,iv:j++mEeMPneyEJOX9sFDomVsZLQjM6QVJBmd3ZIcnr6k=,tag:5A48VsYSQAbpVGe6vaog7Q==,type:str]
authentication_backend:
    file:
        path: ENC[AES256_GCM,data:XXTYQUOxQiwT2C4oHMDLmbqQf5obaD/aEL4=,iv:G6VmoJnL4OFaoAcOOSQ6TnLBts8WaiLtYrOWTrANvpw=,tag:QIIUDdPdUZwLyVn+1tMozw==,type:str]
storage:
    encryption_key: ENC[AES256_GCM,data:b53R9neQdXragPUNYVYQUQnf7JGPvKsirm1s71+q2qT4UWezvVPzNZjWB7zzpcoUYSmJN0mQsh5bgBPF/WYg,iv:IUhj5V8D2aYh63Bp0iRiGmTovOPxkS0NKGhu/UUrgA4=,tag:f3xf5yBixMgqdM/hvjIlfw==,type:str]
    local:
        path: ENC[AES256_GCM,data:bH5/Va71OFxYeiq9AELxiz3p,iv:C6MQyiYjKb1PHLBviCko9GzawW1o7R7NUVrH8PHY4x0=,tag:DosHwwFtq/gFSCcOLB1GaQ==,type:str]
session:
    #ENC[AES256_GCM,data:a5tNl5XE0FImdYMl5PeYjNaDa4hQMX57znP9xSeNk3vVa/hEbVRLZLKGmAFMeRmFkQifWcT/sxnmRDs3EnQ0sO8A3StMTzsWw/M+t8Sen/8l,iv:hPgxM+K/w15ejhRvHUgK4cXQCMOhTJ2ufPtLuQsAchQ=,tag:3nPUF4F/lx3zJNe9U5z7ow==,type:comment]
    secret: ENC[AES256_GCM,data:zefpCHFFEpqwrjuUNco/4PII3jnwUh5aiIC9etHd1PNzgkWlkhIwriJsDndBck+INcQF8tauI+sllgAAK5aj,iv:auzJsFUju5YZLrA6d0k/VOYkfVK1DGo1Oq1Kv33Ve40=,tag:1DDkwG5ZQDRz1nN0hnSF0g==,type:str]
    name: ENC[AES256_GCM,data:zp7EAIUpx/wAs1jFnNhp0A==,iv:lBIV4oXdMqxx42yXvIJ05eIneH4MGDQf5XUZN+xAEcM=,tag:cfFbmdkPmrkXKZ1oYfwmDA==,type:str]
    #ENC[AES256_GCM,data:bUrs/KqP9oULyoQHJe1B5Oy3DqoJSujN9DQHJ9Hs0AWbZb2eDQhPBb38vvKjsM7RVKiF6g==,iv:6ijbeaKQaHFg3IGVtOpjXb4FlTsnJGsfS0R309fp5WA=,tag:EtrVrPmb2pvKVnBeatoTmQ==,type:comment]
    domain: ENC[AES256_GCM,data:agPQUeFU3zQ+,iv:VJBBlzBZztkkUlrjs+n6gTxesE7tu8g+CS1zcvkMuOE=,tag:zoCp5gSx40YAAQu3YNHR6g==,type:str]
    #ENC[AES256_GCM,data:6MDi122nWQ==,iv:vVGrph2pNjk7Gi7tPpBzLc5YAPdlH+H4ScVWgJJE5M0=,tag:s1b0uXvmUUIDHmZoT35gEQ==,type:comment]
    expiration: ENC[AES256_GCM,data:w1zezA==,iv:wphTrzLmAQpw43b4aLt9ZaKcYUK1ltDmDBQGpg35OAo=,tag:EF2vTWy9rdia8BSoOJQ/wA==,type:int]
    #ENC[AES256_GCM,data:/X7ehm7dO7L4KA==,iv:fMIw3x+QGEUMbY1fyBDAK2jHz+uhiHnpkH+AiXOLOo8=,tag:OcY5WDf5HW13h/ZVrlUloQ==,type:comment]
    inactivity: ENC[AES256_GCM,data:HfhB,iv:PHMDl0vZyaMY558D7XUMb3TFWc0h29nUKeZivXamNus=,tag:ZeRoFrEO3S6bLvLHXGdvqA==,type:int]
    redis:
        host: ENC[AES256_GCM,data:SYBbmxY=,iv:vPA3/LggoTgvRTNtwVpW4yJf8k2E5CZFTYAJTlJqafY=,tag:LsbEprINIYpa5WVcFbBWhg==,type:str]
        port: ENC[AES256_GCM,data:8Gedgw==,iv:EO6S7aO9XWd8NtbAXK4G03LGsmyZBf2D8CPt9Ic9nyk=,tag:KBGbTyqJncPXWoil3bAnfA==,type:int]
notifier:
    filesystem:
        filename: ENC[AES256_GCM,data:EAPACSmnoV+ZEVV7kzxFfZqO/OFYWlci,iv:IQGay83ouQifuB+Cijtat2voWZf6xZBQ5mESZI6uywo=,tag:4Zo8z3prZ6k2x2NWS3xWjg==,type:str]
access_control:
    default_policy: ENC[AES256_GCM,data:0mQTzg==,iv:UkSZT2DZFJLEjVOY8uGwVbTD4KNjtyl9/2S6fX6/RPA=,tag:ZRTfsfQpZqz1evnfKayPZQ==,type:str]
    rules:
        - ENC[AES256_GCM,data:bXfo1Ym/wlG7vLS8eiSRJv8BEIjNNVmmCbs=,iv:QA8fx8T6hreRWV0RMv5O7jOLwgo9WbFcKRPKzhoKcs8=,tag:vH72/oqF2BH6Ai8jPmcwCg==,type:comment]
        - domain: ENC[AES256_GCM,data:HXrHNmb7mxybRAUlyQ==,iv:JaMoQY2jRTUMisfivNPGuQKWP8kPi52XlJ5K7oq9Sfs=,tag:tWcZLCsrbIUOA0vDBJc9sw==,type:str]
          policy: ENC[AES256_GCM,data:sIr/FzIn4Sq/tA==,iv:Bz7TAWPeN2X0F11FKyndgckKPTmNG6X0kQNAjg1Ynvs=,tag:Mk47OxnGHNkI9Qjl7KYL2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-07T07:52:56Z"
    mac: ENC[AES256_GCM,data:Y2htzIb9RNDuZfef0huk6n3uhTTQq7BQ0wUbPMb+G80koAU2IJ8d2fTFghKP1KcXboWd+EZwHeOhr2xXUhmaqidrcCkaEi/DOm3C8GqqQN79FEXnxGzVQd9EmRrg7OMk4ZQ9J7rQq0PPbVQaVc6z2VwKbQHU2ZnBY2h+wX1SvbE=,iv:RkI5WfJP26WkwDVgRoVgapc+4q/jAk/x2UYl4WvxUwM=,tag:mHENk8U2L8PHL2Oj37/DSg==,type:str]
    pgp:
        - created_at: "2024-04-07T07:52:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hMIDn615Jx19RhwSBCMEAZHUfaYXjEYI0KKnP1qRr19TPcioneADPuwwpTmDzey1
            M1n86FfP0S1gayhyjSpN/Z6tO1vMCKFovwTbPD+MFsO3AHxZGg8suuAJOMXk+Nm1
            SaxXb5UgwbxYwIbHz9+upk2Lq3oc7ahW3Y2/0ft+UNihZuYNmQTKEjskEsF4UZ2B
            /GchMHR9HZJxE0gXgnMxJ1VXG4y0lc2wolETQSNIlAEPlT+zkvWTX5tHUy8n82xK
            vf8q19JeAeDWizNMMWnpLtueK/e23+AG1Zs1HAlQBHHOOzoMpapBSi5IS1UU6D1q
            4A/CNxLhO2xM8tGjwQ1xnyo/NwwZKm84yBC5JoPnIHCsaiV+aQdxNGYqUB8vdirY
            vytaQw==
            =4yl6
            -----END PGP MESSAGE-----
          fp: F01B47BAD5FC895EE1F1B9E59FAD79271D7D461C
    unencrypted_suffix: _unencrypted
    version: 3.8.1
