---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      enableServiceLinks: false
      containers:
      - name: authelia
        image: authelia/authelia
        ports:
        - containerPort: 9091
        volumeMounts:
          - name: config
            mountPath: "/config"
            subPath: authelia
            readOnly: false
      - name: redis
        image: redis:alpine
        volumeMounts:
          - name: config
            mountPath: "/data"
            subPath: redis
            readOnly: false

      nodeName: homeserver
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: authelia-config
---
apiVersion: v1
kind: Service
metadata:
  name: authelia
spec:
  type: NodePort
  selector:
      app: authelia
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9091
      nodePort: 30001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-all"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - auth.rmtt.tech
    - auth.rmtt.host
    - auth.rmtt.fun
    secretName: authelia-tls
  rules:
  - host: auth.rmtt.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authelia
            port:
              number: 9091
  - host: auth.rmtt.host
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authelia
            port:
              number: 9091
  - host: auth.rmtt.fun
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authelia
            port:
              number: 9091
