---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authelia-config
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/kubernetes_data/authelia
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homeserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-config
spec:
  accessModes:
  - ReadWriteOnce
  volumeName: authelia-config
  volumeMode: Filesystem
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
