secrets:
    nextauth: ENC[AES256_GCM,data:0DHMCAU+0C8FdhbYiHWMhRLKkrEtT1Wj1ii2rCC3EYJ4HAOChYwxf9wXq8XEqe3S,iv:wBN9/gpLlJucOittCsVTOLad51c6zOCddo2ZyzrDFVI=,tag:jyIRVNytk57LcUDlGbD+LQ==,type:str]
    openaiApiKey: ENC[AES256_GCM,data:fHBosw+IlBQy5gthzbl8YyaGehm9SM+y5+U7A7JCPE0Iv3Q=,iv:bmGau6gGh+wqZ2YW+P6Tfn2Etnlb1UpNwhK7+fgL1Jc=,tag:JNWAHD8xliRX3NX2iEoYVg==,type:str]
    openaiBaseUrl: ENC[AES256_GCM,data:eZRcekHnTCykK2qB1s14xYdKtIXnfdI54dObhw==,iv:MWN7mIBNSYTKuZ23bxV8z7aD/rp7FCrych+q3vH4K+8=,tag:/M50kTqerH7xuvdsSvlKmQ==,type:str]
    inferenceTextModel: ENC[AES256_GCM,data:M8cJf2Ybp3+ku3GRlpVxV8R+ag==,iv:Aa4FkMjqr6d18eHQAorWH2nywhRIUS+dcnoDYtdnSAk=,tag:pngv4GSsTqIS7o5QOOFP3g==,type:str]
    inferenceImageModel: ENC[AES256_GCM,data:kxjv/CedEnHGsd7R4ci3QPINhA==,iv:b4j7meHkzNqw0OP5qt4VFddQAwP5Wm7v/+BAkyjLqLU=,tag:co3jsemukNvkjIM58G35sg==,type:str]
    embeddingTextModel: ENC[AES256_GCM,data:zkeH2nwJkJ1W/BsJKfy8V+fNZCkFD+VDIA==,iv:uFxhhxpozFNsUFYnfENG/TGy4F8cp1NgFrTEWjbsp1c=,tag:Yw2qQcMl7pWHzqPjCEtKmw==,type:str]
    oauthWellknownUrl: ENC[AES256_GCM,data:vD+k1ENiBVZqrznacemqiU/D/r6LugcjETW6Gj+H3Mt4fhe/V7SojxqvuPb7oONziIjpDhkVog==,iv:OnIQZk61qyWKdKdtZRHHQ7dhtwxCo2o88uGofEPVUJ8=,tag:3D5l8tP22WJVgP9ULq0xZQ==,type:str]
    oauthClientId: ENC[AES256_GCM,data:/SbuaX+Fb6w=,iv:X6rixiXDLjzCbboN7fEyRbq+ZJwiq4vKq72rKglPFc0=,tag:EzF58oiWJyG8y9EL4Soapw==,type:str]
    oauthClientSecret: ENC[AES256_GCM,data:SbuGHptOk8+MxfKLki/92vdRYLrphPhyR1Rytw==,iv:GX9ivn+lGfFAMz0/b0CCEbyVDQlqPsygUmAzmz3NwA8=,tag:jReHgVDPSuPNBTrYgD5oWQ==,type:str]
    oauthProviderName: ENC[AES256_GCM,data:lKhOTu7R4IQ=,iv:xUKsYDdDmOdc1DZ/ceUVlc+JkiHpN71ogpp4/K6kaBY=,tag:EwUYk5l2iW6CBYvjl80Xdw==,type:str]
nodeSelector:
    kubernetes.io/hostname: ENC[AES256_GCM,data:nOyxo8Wl,iv:M5mCrGL1F/zehWKnytAF3KWxRwQyCNqMtyGK/okIudI=,tag:HhFlLZKElewTSjpCpwjTgw==,type:str]
persistence:
    karakeep:
        enabled: ENC[AES256_GCM,data:OVcm/w==,iv:ldvIfrq0RsFiOxhR04Q4sbPjnl8lJBmSXpa93sJl4y8=,tag:aAZzSViLdN7j4YQ/BQisGA==,type:bool]
        size: ENC[AES256_GCM,data:3n92,iv:fsoi+hhC2HFF0leB/Oo6vYQg062o/HwZQ3OXbZmieZs=,tag:218f52vzg5mv9CZu0AIeiA==,type:str]
    meilisearch:
        enabled: ENC[AES256_GCM,data:M5+bag==,iv:gTNBLrOMApBf7xaXxEnUZsIeWw0fCi8G1hXGj5UoEa4=,tag:i9edkUxCnYO8eIgXPjItDQ==,type:bool]
        size: ENC[AES256_GCM,data:f3nB,iv:JPkVadVSVw1exgMpcvVRv+jWDmAkGgistvhu6GfRNYs=,tag:93WoWD5E1Efj8JpFjN0ehA==,type:str]
sops:
    lastmodified: "2026-05-21T05:44:39Z"
    mac: ENC[AES256_GCM,data:lmXT4z3eEyGRxCVZh22OlNdik+BWo2j3HR1eEhljJ62Bvjnzwf2+Wi71I5YaaRj+lEBxZOHEzHDcJ39yw2OkRvP3tWLbQ367vxlGhk2WjpGpchqI0CmQ1NpVvMSWRsoOm5IdUwSJafC3oDr4rj04mGsw9ne9wbmU2rnS5ZTX5eI=,iv:50xu4y4pbcDGBRw1jChtbF1jSYYs4gYwEjORuvAIoWI=,tag:rZwcSmrirsFFL4AC5FmNMQ==,type:str]
    pgp:
        - created_at: "2026-05-20T13:35:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdA8v+vSZH/Su7XneoLZsiPm02Q0srYIVM0A0UujEI+7ygw
            atvnr+3iWkNe5NqUU9Clwr/UgC7Qk3T2B595LH1HPAHPY8g3M82aiZXF2aLry+2Y
            0lEBlRgC10eNfg834SJalFeu4hMwcH5jxYNdB7W/5YChChIauERCw6HO4L+ph+N2
            dxTB0aM56zvQ1PuPutaCcTNXfbLM7LnZG2rFqdqAvIc1xx8=
            =Eswr
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    unencrypted_suffix: _unencrypted
    version: 3.13.0
