keys:
  - &admin F01B47BAD5FC895EE1F1B9E59FAD79271D7D461C
  - &common_age_for_nixos age1u4gjwdwevlzwfy94lvw69t32rueujk4evypc0r6fuq0nvmua94esge30uk
  - &common_age_for_home_manager age1927atzgxrm04j6z58uj4vzymsw4qavw6nm6qlja3z2dume2wsvyswdgdep

creation_rules:
  - path_regex: services/.*
    pgp: *admin
  - path_regex: home/.*
    age: *common_age_for_home_manager
    pgp: *admin
  - path_regex: nixos/.*
    pgp: *admin
    age: *common_age_for_nixos
  - path_regex: keys/.*
    pgp: *admin
  - pgp: *admin # default
