keys:
  - &admin F01B47BAD5FC895EE1F1B9E59FAD79271D7D461C
  - &common_age age1u4gjwdwevlzwfy94lvw69t32rueujk4evypc0r6fuq0nvmua94esge30uk

creation_rules:
  - path_regex: services/.*
    pgp: *admin
  - age: *common_age
    pgp: *admin
