creation_rules:
  - path_regex: secrets/.*
    key_groups:
    - age:
      - age1u4gjwdwevlzwfy94lvw69t32rueujk4evypc0r6fuq0nvmua94esge30uk
      pgp:
      - F01B47BAD5FC895EE1F1B9E59FAD79271D7D461C
