resources:
  - namespace.yaml
  - volumes.yaml
  - qbittorrent.yaml
  - overseerr.yaml
  - jproxy.yaml
  - prowlarr.yaml
  - flaresolverr.yaml
  - sonarr.yaml
  - radarr.yaml
  - bazarr.yaml

namespace: servarr
commonLabels:
  app: servarr
