---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  labels:
    servarr: overseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      servarr: overseerr
  template:
    metadata:
      labels:
        servarr: overseerr
    spec:
      nodeSelector:
        "kubernetes.io/hostname": homeserver
      containers:
      - name: overseerr
        image: lscr.io/linuxserver/overseerr
        env:
          - name: TZ
            value: "Asia/Shanghai"
        ports:
        - containerPort: 5055
        volumeMounts:
          - name: config
            mountPath: "/config"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: overseerr-config
---
apiVersion: v1
kind: Service
metadata:
  name: overseerr
spec:
  type: ClusterIP
  selector:
      servarr: overseerr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5055
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseerr
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-all"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.middlewares: authentik-ak-outpost-authentik-embedded-outpost@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - v.rmtt.tech
    secretName: overseerr-tls
  rules:
  - host: v.rmtt.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: overseerr
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseerr-public
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-all"
    traefik.ingress.kubernetes.io/router.entrypoints: "public"
    traefik.ingress.kubernetes.io/router.middlewares: authentik-ak-outpost-public-access-for-rmtttech@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - v.rmtt.tech
    secretName: overseerr-tls
  rules:
  - host: v.rmtt.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: overseerr
            port:
              number: 80
