---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    servarr: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      servarr: prowlarr
  template:
    metadata:
      labels:
        servarr: prowlarr
    spec:
      nodeSelector:
        "kubernetes.io/hostname": homeserver
      containers:
      - name: prowlarr
        imagePullPolicy: "Always"
        image: lscr.io/linuxserver/prowlarr:latest
        env:
          - name: TZ
            value: "Asia/Shanghai"
        ports:
        - containerPort: 9696
        volumeMounts:
          - name: config
            mountPath: "/config"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  type: ClusterIP
  selector:
      servarr: prowlarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9696
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-all"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.middlewares: authentik-ak-outpost-authentik-embedded-outpost@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - prowlarr.rmtt.tech
    secretName: prowlarr-tls
  rules:
  - host: prowlarr.rmtt.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr-public
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-all"
    traefik.ingress.kubernetes.io/router.entrypoints: "public"
    traefik.ingress.kubernetes.io/router.middlewares: authentik-ak-outpost-public-access-for-rmtttech@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - prowlarr.rmtt.tech
    secretName: prowlarr-tls
  rules:
  - host: prowlarr.rmtt.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              number: 80
