---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    servarr: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      servarr: qbittorrent
  template:
    metadata:
      labels:
        servarr: qbittorrent
    spec:
      nodeSelector:
        "kubernetes.io/hostname": homeserver
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent
        ports:
        - containerPort: 8080
        env:
          - name: TZ
            value: "Asia/Shanghai"
          - name: PUID
            value: "1000"
        volumeMounts:
          - name: downloads
            mountPath: "/downloads"
          - name: config
            mountPath: "/config"
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: servarr-data-downloads
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  type: ClusterIP
  selector:
      servarr: qbittorrent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-all"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.middlewares: authentik-ak-outpost-authentik-embedded-outpost@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - qb.rmtt.tech
    secretName: qbittorrent-tls
  rules:
  - host: qb.rmtt.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbittorrent
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-public
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-all"
    traefik.ingress.kubernetes.io/router.entrypoints: "public"
    traefik.ingress.kubernetes.io/router.middlewares: authentik-ak-outpost-public-access-for-rmtttech@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - qb.rmtt.tech
    secretName: qbittorrent-tls
  rules:
  - host: qb.rmtt.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbittorrent
            port:
              number: 80
