# following records have different value in public and private net
# public value of those records should be configured in cloudflare
- name: nas
  zone: rmtt.tech
  value: 198.19.19.1
  push: false
- name: pbs
  zone: rmtt.tech
  value: 198.19.19.1
  push: false
- name: homeserver
  zone: rmtt.tech
  value: 198.19.19.1
  push: false
- name: claw
  zone: rmtt.tech
  value: 198.19.19.1
  push: false
- name: status
  zone: rmtt.tech
  value: 198.19.19.1
  push: false
- name: router.proxy
  zone: rmtt.tech
  value: 198.19.19.1
  push: false
- name: ollama
  zone: rmtt.tech
  value: 198.19.19.4
  push: false
- name: k3s.proxy
  zone: rmtt.tech
  value: 198.19.19.4
  push: false
 

# following records have same value in public and private net
- name: homerouter.infra
  zone: rmtt.host
  value: 198.19.19.254
  push: true
- name: homerouter.home
  zone: rmtt.host
  value: 192.168.6.1
  push: true
- name: homeserver.infra
  zone: rmtt.host
  value: 198.19.19.2
  push: true
- name: homeserver-vpro.infra
  zone: rmtt.host
  value: 198.19.19.3
  push: true
- name: labrouter.infra
  zone: rmtt.host
  value: 198.19.19.1
  push: true
- name: kube-runner.infra
  zone: rmtt.host
  value: 198.19.19.4
  push: true
- name: pbs.infra
  zone: rmtt.host
  value: 198.19.19.5
  push: true
- name: nas.infra
  zone: rmtt.host
  value: 198.19.19.6
  push: true
- name: claw.infra
  zone: rmtt.host
  value: 198.19.19.7
  push: true
- name: cn2-box.infra
  zone: rmtt.host
  value: 198.19.198.3
  push: true
- name: cn2-box
  zone: rmtt.host
  value: 104.194.71.122
  push: true
