---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-data
spec:
  capacity:
    storage: 8Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /data/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homeserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  volumeName: plex-data
  storageClassName: local-path
  resources:
    requests:
      storage: 8Ti
