[http.serversTransports.ignorecert]
  insecureSkipVerify = true

[http.routers.traefik-dashboard]
    rule = "Host(`kube-runner.proxy.rmtt.tech`)"
    entryPoints = ["websecure"]
    service = "api@internal"
    tls = { certResolver = "dnsresolver" }

[http.routers.homeserver-pve]
  rule = "Host(`homeserver.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "homeserver-pve"
  tls = { certResolver = "dnsresolver" }

[http.services.homeserver-pve.loadBalancer]
    passHostHeader = true
    serversTransport = "ignorecert"
    [[http.services.homeserver-pve.loadBalancer.servers]]
        url = "https://homeserver.infra.rmtt.host:8006"


[http.routers.nas]
  rule = "Host(`nas.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "nas"
  tls = { certResolver = "dnsresolver" }

[http.services.nas.loadBalancer]
    passHostHeader = true
    [[http.services.nas.loadBalancer.servers]]
        url = "http://nas.infra.rmtt.host"


[http.routers.pbs]
  rule = "Host(`pbs.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "pbs"
  tls = { certResolver = "dnsresolver" }

[http.services.pbs.loadBalancer]
    passHostHeader = true
    serversTransport = "ignorecert"
    [[http.services.pbs.loadBalancer.servers]]
        url = "https://pbs.infra.rmtt.host:8007"

[http.routers.prometheus]
  rule = "Host(`prometheus.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "prometheus"
  tls = { certResolver = "dnsresolver" }
[http.services.prometheus.loadBalancer]
    passHostHeader = true
    [[http.services.prometheus.loadBalancer.servers]]
        url = "http://oracle.infra.rmtt.host:9090"




# services in k3s
[http.middlewares.nextcloud-secure-headers.headers]
  customResponseHeaders = { "X-Frame-Options" = "SAMEORIGIN" }
  stsSeconds = 15552000
  stsIncludeSubdomains = true
  stsPreload = true
  forceSTSHeader = true
  frameDeny = true
  contentTypeNosniff = true
  browserXssFilter = true

[http.routers.nextcloud]
  rule = "Host(`cloud.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "nextcloud"
  middlewares = ["nextcloud-secure-headers"]
  tls = { certResolver = "dnsresolver" }
[http.services.nextcloud.loadBalancer]
  passHostHeader = true
  [[http.services.nextcloud.loadBalancer.servers]]
    url = "http://kube-runner.infra.rmtt.host:30000"


[http.middlewares.authelia.forwardAuth]
  address = "http://kube-runner.infra.rmtt.host:30002/api/authz/forward-auth"
  trustForwardHeader = true
  maxResponseBodySize = 8192
  authResponseHeaders = ["Remote-User", "Remote-Groups", "Remote-Email", "Remote-Name"]
[http.routers.authelia]
  rule = "Host(`auth.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "authelia"
  tls = { certResolver = "dnsresolver" }
[http.services.authelia.loadBalancer]
  passHostHeader = true
  [[http.services.authelia.loadBalancer.servers]]
    url = "http://kube-runner.infra.rmtt.host:30002"
