hostname: ENC[AES256_GCM,data:zv6uvLxxdaUm,iv:FIwouxp1ZTQ5nusbdn48P0QgXQTavtcpNiVG1M+LLpc=,tag:mLzLL1aGMJcOBXL8QSBgnQ==,type:str]
app_url: ENC[AES256_GCM,data:jB9aIPUq+DBO3R8fUw==,iv:dOAsk7WmHGzrX/NX+9qec9x3BFs19Ks1ydZjdeaZfWw=,tag:EMF8WXMm3d3e1phFYFWI5A==,type:str]
encryption_key: ENC[AES256_GCM,data:jbyEBBIjusaOzuJ1bEE+rLSrv4F7fQG8eVIfKbVix3G3zw3jS3yejnbCTiA=,iv:YcS8kahkoV1fpjQFNjTgIN29Qbfj5kPjoDRJgic/nUs=,tag:D2VXZiVr3iXWDl79mhA5DA==,type:str]
sops:
    lastmodified: "2026-01-18T03:43:58Z"
    mac: ENC[AES256_GCM,data:2r0Ld/3hLJ+WzBrG3phR71o8VxQ4z8UEYBd9sZPDdEGfPI5fUQtVWnSwEXLoM7e2zCSh/aBrZwPCDLvsGtAR9iuAM1pL/7ncgn89fHcGyOxKEoG4wEMwfvpYq6AhfBXs0dAuA15PyV+LhvJIG8Ty0ybo3aVyWmsKy03C/CxZEG0=,iv:TFotkf3tc2MvMscwrO9wOKEQnaH+j+Il6FOLy4QABR4=,tag:VNXDS6ulH70qKIMu+vxT1g==,type:str]
    pgp:
        - created_at: "2026-01-22T16:53:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D36+3H3ly1I0SAQdAhmyhRnBdq8f5hezEAt+fiecc+jqSTgAjC633zf8YPXgw
            xfkX4deOo4ZdyYYqBoHAaritfS7tMWF3Sqa1FMCOZaIoJXUFG5VIvyLtcl37mLvA
            0l4BgxvMTZkrtr8yxC33tW6c13CrzklGdu6UUZm+PWRQdpuA4s3l5koG9/wU5VsP
            uFWbAsAZPCjkzfWAqhq4Eletfy1IHK15aI994TY++yBl/LeP6e5NvR53S5DlkxgV
            =vixc
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    unencrypted_suffix: _unencrypted
    version: 3.11.0
