[http.serversTransports.ignorecert]
  insecureSkipVerify = true

[http.routers.traefik-dashboard]
    rule = "Host(`homeserver.proxy.rmtt.tech`)"
    entryPoints = ["websecure"]
    service = "api@internal"
    tls = { certResolver = "dnsresolver" }


# services in k3s
[http.middlewares.authelia.forwardAuth]
  address = "http://homeserver.infra.rmtt.host:30002/api/authz/forward-auth"
  trustForwardHeader = true
  maxResponseBodySize = 8192
  authResponseHeaders = ["Remote-User", "Remote-Groups", "Remote-Email", "Remote-Name"]
[http.routers.authelia]
  rule = "Host(`auth.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "authelia"
  tls = { certResolver = "dnsresolver" }
[http.services.authelia.loadBalancer]
  passHostHeader = true
  [[http.services.authelia.loadBalancer.servers]]
    url = "http://homeserver.infra.rmtt.host:30002"
