[http.serversTransports.ignorecert]
  insecureSkipVerify = true

[http.routers.traefik-dashboard]
    rule = "Host(`kube-runner.proxy.rmtt.tech`)"
    entryPoints = ["websecure"]
    service = "api@internal"
    tls = { certResolver = "dnsresolver" }

[http.routers.homeserver-pve]
  rule = "Host(`homeserver.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "homeserver-pve"
  tls = { certResolver = "dnsresolver" }

[http.services.homeserver-pve.loadBalancer]
    passHostHeader = true
    serversTransport = "ignorecert"
    [[http.services.homeserver-pve.loadBalancer.servers]]
        url = "https://homeserver.infra.rmtt.host:8006"


[http.routers.pbs]
  rule = "Host(`pbs.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "pbs"
  tls = { certResolver = "dnsresolver" }

[http.services.pbs.loadBalancer]
    passHostHeader = true
    serversTransport = "ignorecert"
    [[http.services.pbs.loadBalancer.servers]]
        url = "https://pbs.infra.rmtt.host:8007"

[http.routers.prometheus]
  rule = "Host(`prometheus.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "prometheus"
  tls = { certResolver = "dnsresolver" }
[http.services.prometheus.loadBalancer]
    passHostHeader = true
    [[http.services.prometheus.loadBalancer.servers]]
        url = "http://oracle.infra.rmtt.host:9090"

# services in k3s
[http.middlewares.nextcloud-secure-headers.headers]
  customResponseHeaders = { "X-Frame-Options" = "SAMEORIGIN" }
  stsSeconds = 15552000
  stsIncludeSubdomains = true
  stsPreload = true
  forceSTSHeader = true
  frameDeny = true
  contentTypeNosniff = true
  browserXssFilter = true

[http.middlewares.authelia.forwardAuth]
  address = "http://kube-runner.infra.rmtt.host:30002/api/authz/forward-auth"
  trustForwardHeader = true
  maxResponseBodySize = 8192
  authResponseHeaders = ["Remote-User", "Remote-Groups", "Remote-Email", "Remote-Name"]
[http.routers.authelia]
  rule = "Host(`auth.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "authelia"
  tls = { certResolver = "dnsresolver" }
[http.services.authelia.loadBalancer]
  passHostHeader = true
  [[http.services.authelia.loadBalancer.servers]]
    url = "http://kube-runner.infra.rmtt.host:30002"


[http.routers.n8n]
  rule = "Host(`workflow.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "n8n"
  tls = { certResolver = "dnsresolver" }
[http.services.n8n.loadBalancer]
  passHostHeader = true
  [[http.services.n8n.loadBalancer.servers]]
    url = "http://kube-runner.infra.rmtt.host:30003"


[http.routers.miniflux]
  rule = "Host(`miniflux.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "miniflux"
  tls = { certResolver = "dnsresolver" }
[http.services.miniflux.loadBalancer]
  passHostHeader = true
  [[http.services.miniflux.loadBalancer.servers]]
    url = "http://kube-runner.infra.rmtt.host:30004"

