apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud
spec:
  entryPoints:
    - websecure
  tls:
    secretName: nextcloud-tls
  routes:
    - match: Host(`{{ .Values.nextcloud.nextcloud.host }}`)
      kind: Rule
      services:
        - name: nextcloud
          port: 8080
      middlewares:
        - name: nextcloud-secure-headers
          namespace: {{ .Release.Namespace }}
