apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas
  resources:
    requests:
      storage: 2048Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-configuration
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
