apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-db
  annotations:
    "helm.sh/resource-policy": keep
spec:
  instances: 1
  storage:
    storageClass: local-path
    size: 5Gi
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
  affinity:
    nodeSelector:
      kubernetes.io/hostname: "kube-runner"
