apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api"
      - "--api.insecure=true"
    ports:
      public:
        port: 20000
        hostPort: 1443
        exposedPort: 1443
        protocol: TCP
        tls:
           enabled: true
      web:
        hostPort: 80
      websecure:
        hostPort: 443

    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    deployment:
      replicas: 3
    service:
      type: NodePort
