[http.serversTransports.ignorecert]
  insecureSkipVerify = true

[http.routers.traefik-dashboard]
    rule = "Host(`oracle.proxy.rmtt.tech`)"
    entryPoints = ["websecure"]
    service = "api@internal"
    tls = { certResolver = "dnsresolver" }

[http.routers.uptime]
  rule = "Host(`status.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "uptime"
  tls = { certResolver = "dnsresolver" }

[http.services.uptime.loadBalancer]
    passHostHeader = true
    [[http.services.uptime.loadBalancer.servers]]
        url = "http://oracle.infra.rmtt.host:8090"

[http.routers.grafana]
  rule = "Host(`grafana.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "grafana"
  tls = { certResolver = "dnsresolver" }
[http.services.grafana.loadBalancer]
    passHostHeader = true
    [[http.services.grafana.loadBalancer.servers]]
        url = "http://oracle.infra.rmtt.host:3000"

[http.routers.prometheus]
  rule = "Host(`prometheus.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "prometheus"
  tls = { certResolver = "dnsresolver" }
[http.services.prometheus.loadBalancer]
    passHostHeader = true
    [[http.services.prometheus.loadBalancer.servers]]
        url = "http://oracle.infra.rmtt.host:9090"


# services in k3s
[http.middlewares.authelia.forwardAuth]
  address = "http://oracle.infra.rmtt.host:30002/api/authz/forward-auth"
  trustForwardHeader = true
  maxResponseBodySize = 8192
  authResponseHeaders = ["Remote-User", "Remote-Groups", "Remote-Email", "Remote-Name"]
[http.routers.authelia]
  rule = "Host(`auth.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "authelia"
  tls = { certResolver = "dnsresolver" }
[http.services.authelia.loadBalancer]
  passHostHeader = true
  [[http.services.authelia.loadBalancer.servers]]
    url = "http://oracle.infra.rmtt.host:30002"
[http.routers.karakeep]
  rule = "Host(`karakeep.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "karakeep"
  tls = { certResolver = "dnsresolver" }
[http.services.karakeep.loadBalancer]
  passHostHeader = true
  [[http.services.karakeep.loadBalancer.servers]]
    url = "http://oracle.infra.rmtt.host:30001"


[http.routers.miniflux]
  rule = "Host(`miniflux.rmtt.tech`)"
  entryPoints = ["websecure"]
  service = "miniflux"
  tls = { certResolver = "dnsresolver" }
[http.services.miniflux.loadBalancer]
  passHostHeader = true
  [[http.services.miniflux.loadBalancer.servers]]
    url = "http://oracle.infra.rmtt.host:30004"
