---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddns-go-homeserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddns-go-homeserver
  template:
    metadata:
      labels:
        app: ddns-go-homeserver
    spec:
      hostNetwork: true
      containers:
      - name: ddns-go
        image: jeessy/ddns-go
        command: ["/app/ddns-go","-l", ":9876", "-f", "300", "-dns", "223.5.5.5"]
        ports:
        - containerPort: 9876
        volumeMounts:
          - name: config
            mountPath: "/root"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: ddns-go-config
---
apiVersion: v1
kind: Service
metadata:
  name: ddns-go-homeserver
spec:
  type: ClusterIP
  selector:
      app: ddns-go-homeserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9876
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ddns-go-homeserver
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-all"
    nginx.ingress.kubernetes.io/auth-method: 'GET'
    nginx.ingress.kubernetes.io/auth-url: 'http://authelia.authelia.svc.cluster.local/api/authz/auth-request'
    nginx.ingress.kubernetes.io/auth-signin: 'https://auth.rmtt.host:1443?rm=$request_method'
    nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - ddns.homeserver.rmtt.host
    secretName: ddns-go-homeserver-tls
  rules:
  - host: ddns.homeserver.rmtt.host
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ddns-go-homeserver
            port:
              number: 9876
