---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddns-go-homeserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddns-go-homeserver
  template:
    metadata:
      labels:
        app: ddns-go-homeserver
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: homeserver
      containers:
      - name: ddns-go
        image: jeessy/ddns-go
        command: ["/app/ddns-go","-l", ":9876", "-f", "300", "-dns", "223.5.5.5"]
        ports:
        - containerPort: 9876
        volumeMounts:
          - name: config
            mountPath: "/root"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: ddns-go-config
---
apiVersion: v1
kind: Service
metadata:
  name: ddns-go-homeserver
spec:
  type: ClusterIP
  selector:
      app: ddns-go-homeserver
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9876
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ddns-go-homeserver
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-all"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - ddns.homeserver.rmtt.host
    secretName: ddns-go-homeserver-tls
  rules:
  - host: ddns.homeserver.rmtt.host
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ddns-go-homeserver
            port:
              number: 80
