resources:
  - namespace.yaml
  - volumes.yaml
  - middlewares.yaml

namespace: nextcloud
commonLabels:
  app: nextcloud

patches:
  - path: ./patches/ingress.yaml

helmCharts:
  - name: nextcloud
    repo: https://nextcloud.github.io/helm/
    releaseName: nextcloud
    valuesFile: values.yaml.dec
    version: 5.5.0
