# reference https://github.com/nextcloud/helm/tree/main/charts/nextcloud
nextcloud:
  nodeSelector:
    kubernetes.io/hostname: kube-runner

  nextcloud:
    host: cloud.rmtt.tech
    trustedDomains: "cloud.rmtt.tech"
    defaultConfigs:
      redis.config.php: false
    # make defaultConfigs works
    configs:
      custom.config.php: |-
        <?php
        $CONFIG = array (
          'maintenance_window_start' => 1,
          'default_phone_region' => 'US',
          'serverid' => 1,
          'overwriteprotocol' => 'https',
          'overwrite.cli.url' => 'https://cloud.rmtt.tech',
          'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          'trusted_proxies' => array('10.42.0.0/16', '10.43.0.0/16'),
        );

  ## External database configuration
  internalDatabase:
    enabled: false
  externalDatabase:
    enabled: true
    type: postgresql
    host: nextcloud-db-rw
    database: nextcloud
    existingSecret:
      enabled: true
      secretName: nextcloud-db-app
      usernameKey: username
      passwordKey: password

  cronjob:
    enabled: true

  mariadb:
    enabled: false
  postgresql:
    enabled: false
  redis:
    enabled: false

  ## Enable persistence using Persistent Volume Claims
  persistence:
    enabled: true
    existingClaim: nextcloud-configuration
    nextcloudData:
      enabled: true
      existingClaim: nextcloud-data
