service:
    nodePort: ENC[AES256_GCM,data:JlYHe2M=,iv:JKFm08jvlqc0grDV7ENAr8mrO3lC+Aq1n56MaANi3+Q=,tag:5hUVGzCGc5UiBDxRdnD9tw==,type:int]
database:
    size: ENC[AES256_GCM,data:g8A/,iv:JTf8Zz8wFcP/1C3R9CQRMhI35/etSzW2MLNZQBsdkTU=,tag:TZL2h79al4zJ5kFMAXzHow==,type:str]
    storageClassName: ENC[AES256_GCM,data:849uJjE4ybjiiA==,iv:pQMgCprZ8uLUO0rNwNLV2O1xpXojXTigCrrPYu3RG8o=,tag:j3maYsuH2GFpdWsOF3oNiA==,type:str]
nodeSelector:
    kubernetes.io/hostname: ENC[AES256_GCM,data:JTolO7WO8o42ybk=,iv:aOs/Ckn1V45F4+mt6qieTP9uAU/wEGQjWhpTYLpfg/8=,tag:fX1XTbv6ztOzXpAEXnw7KQ==,type:str]
secrets:
    adminUsername: ENC[AES256_GCM,data:PCo=,iv:WcouqDfGsqsvHfSP3PXTs0+qvWfTLg0ubZEhrLLPk78=,tag:QKxtKUF/JqKX21vrbAPgew==,type:str]
    adminPassword: ENC[AES256_GCM,data:VxWHcduqNj3QZLA=,iv:FqnxI0Ty0XFsht+v7CaxMxvANEjXPXk7GWKqeZGXHcc=,tag:I2u2zH7dmsz0qFXBhpYxtw==,type:str]
env: []
sops:
    lastmodified: "2026-05-23T09:20:07Z"
    mac: ENC[AES256_GCM,data:QyoC1cQDhbdSD3ugw5lT7GA/pH3bKv4rnQ4tVBDMUg19i5gaR2wAiuoDxQt9HD3BAgCNeZrWid1wCGLm6LijdqivE9vxJnBXPQyc9rs/wT7A3sOb6MFlSJ++p5bNSY65HHzIJvWY/oQum7E/yL/fjLc81E+LsH+9aoNqbn51pyg=,iv:nDOoIlkrs8ru1E9Op1vWKfnQwZWf+EdqHyjgh3miR9s=,tag:stxcZwDzPDotT0qGdzX5gg==,type:str]
    pgp:
        - created_at: "2026-05-23T09:19:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAl4dILyUERg3E7UAe9WZenkgL0ypEy7bsWgC2+g33Lnww
            H4/HD6iIDX+hCH7Py2n/BhhaTcovqmiNWhFDkZ3J3G6Acyj1YmkOm7nDfjCk9Fvy
            0lEBDrMyIOcLeUoNjgOTeSSGDSf31XA6t4s5/U1OvAh9Yk1pw5yeGBOMHupUs+I/
            NBeYhbCnHT/oJ303uV2IVFqlulTjbkXBvhDNK3UtSFU6w6s=
            =Jt1W
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    unencrypted_suffix: _unencrypted
    version: 3.13.0
