cert-manager:
    global:
        nodeSelector:
            kubernetes.io/hostname: ENC[AES256_GCM,data:c/72tZQp,iv:675KaV8y/Ca2jHSzQLujYBYNCFi08/aQAS0GQIoLKus=,tag:yTx5aLjx8LTvBc6xHJ/mzg==,type:str]
    crds:
        enabled: ENC[AES256_GCM,data:BeJ52A==,iv:epRQfoggpdRsaYwE+hSxK2TWOeWMBGTHi06BP3vLNmc=,tag:XPMya0wcOMB+2XT7yzO01g==,type:bool]
cloudflare:
    email: ENC[AES256_GCM,data:fyZOktJpZaGSoEUQ7UZThtKT,iv:Xlemv5PrHEInYndZHpStdmBDvD+tcgdjXVRBhVp9sOo=,tag:AoEmJiVpJ7DFJLdEPTBPYQ==,type:str]
    token: ENC[AES256_GCM,data:Ix/eIVaIDyPY00p7FdnwOdEJD9KUSnzRFIt4r4zNXpv1qusO1eIW52TQDxaCoJBSpZCmrtI=,iv:kzCNp48WAZuF3zuza1sFX5ug4xCYJbtCzAx4SWJ1qkw=,tag:3edLv/H2qOdIFfruHm1hGQ==,type:str]
sops:
    lastmodified: "2026-05-19T09:11:46Z"
    mac: ENC[AES256_GCM,data:zeT+5rAB2hKcgeojHVtCSnxQOX9o1NcKpukxu2VEUeZc4yZPTmXH2yEUP1DMijK3MnPYjkNztGoYtOb8aBchJ7UC3yBXxEZcTc7trLJrI2+bp24J8GA17TiBoxUN6HFletmvH/h+U9OkEJr5+TfwKC7rJdr3VE789rrIphV1Bck=,iv:qsMlbFbdW8uAMx2wd7GlZiNF7U6NLN2oVfrjVTiV4ow=,tag:yS25B/prV1DOd00JO9eNfw==,type:str]
    pgp:
        - created_at: "2026-05-19T05:27:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdA2X3Wmg53gCdSpgZ4u3xKpbnz5bXVpkhUG8fDBkUWq3Uw
            IrK9dKRfBQDyCEs74NFgOzl6BUVSYyUxf1VDz42CIDOcmNI0wWK6kHaiXf+umh45
            0lEBNP7S/XEqtN0pKRrSfJHShCybeSPvKRV5ShwhBab657djlMAqSjM2J37YeAXR
            B8Z9wv1uA+vvOBOpU8NCOY9HRbgn6KknHqEwsjqxevwSOcI=
            =0IR1
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    unencrypted_suffix: _unencrypted
    version: 3.12.2
