version: '3'

services:
  portainer:
    image: portainer/portainer-ee:latest
    networks:
      - web
    ports:
      - 9000:9000
    environment:
      - TZ="Asia/Shanghai"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ${DOCKER_DATA_PATH}/portainer:/data
    restart: unless-stopped

networks:
  web:
    name: web
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.1/24
