resources:
  - namespace.yaml

namespace: authentik
helmCharts:
  - name: authentik
    releaseName: authentik
    namespace: authentik
    repo: https://charts.goauthentik.io
    version: 2024.12.1
    valuesFile: values.yaml.dec
