resources:
  - namespace.yaml

namespace: homarr
commonLabels:
  app.kubernetes.io/name: homarr

helmCharts:
  - name: homarr
    releaseName: homarr
    repo: https://oben01.github.io/charts
    version: 1.2.5
    valuesInline:
      persistence:
        - name: homarr-config
          enabled: true
          storageClassName: local-path
          accessMode: ReadWriteOnce
          size: "50Mi"
          mountPath: "/app/data/configs"
        - name: homarr-database
          enabled: true
          storageClassName: local-path
          accessMode: "ReadWriteOnce"
          size: "50Mi"
          mountPath: "/app/database"
        - name: homarr-icons
          enabled: true
          storageClassName: "local-path"
          accessMode: "ReadWriteOnce"
          size: "50Mi"
          mountPath: "/app/public/icons"
      ingress:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-all"
          traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
        hosts:
          - host: rmtt.tech
            paths:
              - path: /
          - host: rmtt.fun
            paths:
              - path: /
        tls:
          - hosts:
            - "rmtt.tech"
            # - "rmtt.fun"
            secretName: homarr-tls
