apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17-bullseye
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
  affinity:
    nodeSelector:
        "kubernetes.io/hostname": homeserver
  storage:
    size: 50Gi
    storageClass: local-path
  backup:
    barmanObjectStore:
      destinationPath: s3://mtsdatabase-backup
      endpointURL: https://s3.us-east-005.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nextcloud
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: nextcloud
