apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pocket-id
spec:
  instances: 1

  affinity:
    nodeSelector:
      kubernetes.io/hostname: "homeserver"

  storage:
    storageClass: local-path
    size: 5Gi
