cloudflare-token: ENC[AES256_GCM,data:grPoUi/4JlHghvinUSK2VnS3bwM9M9ixnkCzMX20f/bMm7/K0Y8t6w==,iv:SUx+UzgOm/y2P28RiHWnfuYPC4uL4+yyOflNiubklrQ=,tag:qdlKRCEr74PICJrAdPy8BQ==,type:str]
cloudflare-zone-id: ENC[AES256_GCM,data:2tLY7vShwcGRKfKETI4/5pjWkv6tcsCBvtl2Rhs+tw4=,iv:++tecphwEUbLc7mjtgF+UZZ9QM2kwGTLxAuCj0Kz4PI=,tag:AYdedfnkgGj4tSWb8hWbHg==,type:str]
cloudflare-ddns-domains: ENC[AES256_GCM,data:BNamexH3o0zrSSFv37/23Jcs0OQFhfzu7c8WpwJL6oRoDHQU5BzoGC/Zx828p8tnQvFqL1iC/GnEIjEch5rPcGVI,iv:oQEK/FA1sJiziieC6AeNydUXxkKM28XJJGmsmGI0BDg=,tag:Zkhf/eyFg9XapL1dsuxK1Q==,type:str]
mt-pass: ENC[AES256_GCM,data:NErIQcG4uRT+hHQTC9S8ntZaqw0ci8q4yCY1Y/B0GcfwC8mZv6AuS9czjG8QKCAXcJs/bJu+4Ng5058f1hboeaIY6twB1aUyWh4IBsJ49h5yOAlaAdDtLkUslB2bILNzrzVCGHJeq8BGiw==,iv:z+nwQbZo/odEGy4XrAzAo9qXQx6XOEWSmMZGXV7n/kw=,tag:ymJZmYvzjLZkxNRKY4+3tA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u4gjwdwevlzwfy94lvw69t32rueujk4evypc0r6fuq0nvmua94esge30uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMDNmb3BVUHM2L3JqREhl
            aEhKa1poL1pNck90bzZUUzl3NGE3MUIxbmxNCjhWR3h5OXF0NUxhbEc2dGJSeFJG
            NkVGeFhzSEx4ek84RGVsVVZGdTBjUGcKLS0tIHFCODRwYnRIVitZRjBmWnNXMXE1
            RjF4eTR1OHN2WjMyaEVBZlNhV0hoMTAK+/RdnyAeiQUJ3S+zE2tBeATRVyu5kq3b
            BiAnhADkWGndAUUgVuIZbAtpWL3fKZDw7Q06uEKDNMai07YIFmt72Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-03T12:52:36Z"
    mac: ENC[AES256_GCM,data:4YnCuv85/u3WQGy1yk7ABIdtUjoVHEYMmpfFIlJC5DcwUK7qS3/b8q53ayiC8bphyXit7ifQVgJHjA2bvScMbM3vkYajxjW6bBuY0MH4oWXLmFhWpUsE1mEkaxswruPR8zUm+IGk9L7jMhPZtjBaaG8Cu7NcpHFAV11prS1qSoI=,iv:zQJkPYIos1wJ+gkrt469H7VFbVihLJdmqFaCoCeP1xQ=,tag:iT+SxwbApTvhdGTTt15GSA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
