cloudflare-token: ENC[AES256_GCM,data:grPoUi/4JlHghvinUSK2VnS3bwM9M9ixnkCzMX20f/bMm7/K0Y8t6w==,iv:SUx+UzgOm/y2P28RiHWnfuYPC4uL4+yyOflNiubklrQ=,tag:qdlKRCEr74PICJrAdPy8BQ==,type:str]
cloudflare-zone-id: ENC[AES256_GCM,data:2tLY7vShwcGRKfKETI4/5pjWkv6tcsCBvtl2Rhs+tw4=,iv:++tecphwEUbLc7mjtgF+UZZ9QM2kwGTLxAuCj0Kz4PI=,tag:AYdedfnkgGj4tSWb8hWbHg==,type:str]
cloudflare-ddns-domains: ENC[AES256_GCM,data:eQ7C81RwH2dgHEe98TePLCbYpslo6pt+MpCKCRiDnqLHX/Fs2Ir3LNJj4S1X7gT5OFADNpZ68zcQRt+C/bSpto5iWhidE1Z9d+n860LqY9G6lnNFDezEqtRGP+FXRFxsCTU7/e7Znh21vCL5SfV7yy5Jyk8PCw==,iv:CnB3ZalIwFz9CvNk6siBcy/nK9viXfFNnOAF89j6Yns=,tag:OzLpN4Jq1OTcetcYz5jcTw==,type:str]
mt-pass: ENC[AES256_GCM,data:NErIQcG4uRT+hHQTC9S8ntZaqw0ci8q4yCY1Y/B0GcfwC8mZv6AuS9czjG8QKCAXcJs/bJu+4Ng5058f1hboeaIY6twB1aUyWh4IBsJ49h5yOAlaAdDtLkUslB2bILNzrzVCGHJeq8BGiw==,iv:z+nwQbZo/odEGy4XrAzAo9qXQx6XOEWSmMZGXV7n/kw=,tag:ymJZmYvzjLZkxNRKY4+3tA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u4gjwdwevlzwfy94lvw69t32rueujk4evypc0r6fuq0nvmua94esge30uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6V2JEaXM2ek1SU21Kamt5
            K2V5N0xaY0hnbG1ja01HQitUYzIxWDgvR2c0CjR6bFhBdVAwNm1zc3k2VFBmTUpz
            Yi81TXZPMm9ZTFN1aVpoV0kzTG1iS3cKLS0tIGdFZlQvWVB5VmJlbXFUUFZldFd2
            TEY1WUhhdG5XSFpQL3FOb3lxRm9ETlEKUYoU+dFJuF/aOQPZtVHqlHO9JGQs2K2I
            SN5qlwUUZfEOwiM5ZYISzGibEAPm862Z2A4SLzgKBLI1KpoXQXDBYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-15T04:51:58Z"
    mac: ENC[AES256_GCM,data:tNzCo0fEObwAatLjuiNT2aDsQgL4aqj4h3MGv3E5T75h6/bF+hmi2MYMJxOhNCaUb8kGR6+qSoDHLMdDyThzIyVZNrcHTUrJGtZ0JhrYxDgLVQA6xUMpD9CKAObFVnjdPa3QMsBeaGjwphvaVnvJZc45v5GIrQbZrdairnMk4JA=,iv:gSX96iMYjL6omnb2aYEneRnwHNGzMr9s/EPp0YioOnk=,tag:WGWDwQ7CUYQx+Aw07OnH9w==,type:str]
    pgp:
        - created_at: "2023-07-26T06:55:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hMIDn615Jx19RhwSBCMEAVTDLPidhQKtjruiJut23QOwaYsSzVLEPppg156w+UQn
            r8yGyckCaj5DhzsQrmnXxjXNp2PzltBxmBROKeYUDbKbAXUkJ1wF6+My/UCj8y97
            vPb7p2GmMNH/J8nzwmsYT4+1dUBmu/6rl8loukPW0h+1+ugYrNqYd69piDGxYPsc
            7D3ZMFsYnwWAEXUZXmYBhbclAbwpyXI0JwD539c0rMRu2WMRmLpgnen2NjdYX5h7
            WI93LdJeAbMjYyLOERngl+/jKWWA/2z4TkTHnr2AMvW2pKbk8n6X91Emyr5XI2rJ
            vkHinxCwDmaC+eUbGW4035WZ3g090fHKibMiTVOck4rmGA3UiXqI4zulYTjmXwYv
            o39Q+A==
            =iosj
            -----END PGP MESSAGE-----
          fp: F01B47BAD5FC895EE1F1B9E59FAD79271D7D461C
    unencrypted_suffix: _unencrypted
    version: 3.7.3
