cloudflare-token: ENC[AES256_GCM,data:grPoUi/4JlHghvinUSK2VnS3bwM9M9ixnkCzMX20f/bMm7/K0Y8t6w==,iv:SUx+UzgOm/y2P28RiHWnfuYPC4uL4+yyOflNiubklrQ=,tag:qdlKRCEr74PICJrAdPy8BQ==,type:str]
cloudflare-zone-id: ENC[AES256_GCM,data:2tLY7vShwcGRKfKETI4/5pjWkv6tcsCBvtl2Rhs+tw4=,iv:++tecphwEUbLc7mjtgF+UZZ9QM2kwGTLxAuCj0Kz4PI=,tag:AYdedfnkgGj4tSWb8hWbHg==,type:str]
cloudflare-ddns-domains: ENC[AES256_GCM,data:BNamexH3o0zrSSFv37/23Jcs0OQFhfzu7c8WpwJL6oRoDHQU5BzoGC/Zx828p8tnQvFqL1iC/GnEIjEch5rPcGVI,iv:oQEK/FA1sJiziieC6AeNydUXxkKM28XJJGmsmGI0BDg=,tag:Zkhf/eyFg9XapL1dsuxK1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u4gjwdwevlzwfy94lvw69t32rueujk4evypc0r6fuq0nvmua94esge30uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMDNmb3BVUHM2L3JqREhl
            aEhKa1poL1pNck90bzZUUzl3NGE3MUIxbmxNCjhWR3h5OXF0NUxhbEc2dGJSeFJG
            NkVGeFhzSEx4ek84RGVsVVZGdTBjUGcKLS0tIHFCODRwYnRIVitZRjBmWnNXMXE1
            RjF4eTR1OHN2WjMyaEVBZlNhV0hoMTAK+/RdnyAeiQUJ3S+zE2tBeATRVyu5kq3b
            BiAnhADkWGndAUUgVuIZbAtpWL3fKZDw7Q06uEKDNMai07YIFmt72Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-09T08:43:57Z"
    mac: ENC[AES256_GCM,data:pvA0v7M1rL871ZNzW3dn99KteDim6gIp7LUxWcFPgb90L4loUdt8Z4fMkErJkOfX5a+p1CMow4mrnolhBijw/Cf/hpA5c+lCBAAiXd9qPYoK/meY2Hkyb/6P39jQ7dMknIs8u0fRDwy6yt33HXCHbPncr2KahwIQ1EQOLiWx9/w=,iv:Tmr1nse+ca34c4J5VojyxY2/LOJA9fqoJ69HX1vgOlg=,tag:EM0phS4fYCmsddxFz+WOeA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
