cloudflare-token: ENC[AES256_GCM,data:grPoUi/4JlHghvinUSK2VnS3bwM9M9ixnkCzMX20f/bMm7/K0Y8t6w==,iv:SUx+UzgOm/y2P28RiHWnfuYPC4uL4+yyOflNiubklrQ=,tag:qdlKRCEr74PICJrAdPy8BQ==,type:str]
cloudflare-zone-id: ENC[AES256_GCM,data:2tLY7vShwcGRKfKETI4/5pjWkv6tcsCBvtl2Rhs+tw4=,iv:++tecphwEUbLc7mjtgF+UZZ9QM2kwGTLxAuCj0Kz4PI=,tag:AYdedfnkgGj4tSWb8hWbHg==,type:str]
cloudflare-ddns-domains: ENC[AES256_GCM,data:ktxQ7qT8HxAFjgAQVgZ81RLOOOkliLsu5KRUoKYPjIXRW4B4okJp+mafR3p2V7e6H1YU3p5gAYSt0whtQh4bBqN7ntkZICnDWiiFjp96hrkK8dLRAO456M1EflS7sfmzJ2Q=,iv:m5QDqcJMl5Ct6hTdyk/Rrp7qUoY6JIrEwxdF5rnqF9o=,tag:Q1b0x1PliceJwF6y3QI8Og==,type:str]
mt-pass: ENC[AES256_GCM,data:NErIQcG4uRT+hHQTC9S8ntZaqw0ci8q4yCY1Y/B0GcfwC8mZv6AuS9czjG8QKCAXcJs/bJu+4Ng5058f1hboeaIY6twB1aUyWh4IBsJ49h5yOAlaAdDtLkUslB2bILNzrzVCGHJeq8BGiw==,iv:z+nwQbZo/odEGy4XrAzAo9qXQx6XOEWSmMZGXV7n/kw=,tag:ymJZmYvzjLZkxNRKY4+3tA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u4gjwdwevlzwfy94lvw69t32rueujk4evypc0r6fuq0nvmua94esge30uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMDNmb3BVUHM2L3JqREhl
            aEhKa1poL1pNck90bzZUUzl3NGE3MUIxbmxNCjhWR3h5OXF0NUxhbEc2dGJSeFJG
            NkVGeFhzSEx4ek84RGVsVVZGdTBjUGcKLS0tIHFCODRwYnRIVitZRjBmWnNXMXE1
            RjF4eTR1OHN2WjMyaEVBZlNhV0hoMTAK+/RdnyAeiQUJ3S+zE2tBeATRVyu5kq3b
            BiAnhADkWGndAUUgVuIZbAtpWL3fKZDw7Q06uEKDNMai07YIFmt72Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T17:42:03Z"
    mac: ENC[AES256_GCM,data:DUDKgejp0hsLjtFzKMhMv2GjWZaEZUyjXLvGiRKiVIPzXfzSyLL4yTne+9EaZsrhU2U5vEkV0dEAKtA8almKrfbKi0caBGCJpE3k8y7HGosb0PyF65VVL7tNx4nWAvLCI1AnY8Wl/rYCIAgMfnu1ZopV7fyeRhnQs0tJG6uPIoM=,iv:rJrQ5uFh7Wxa82qbLJAwITsrlwKnsE0wdD+MEjzAxRM=,tag:byK4pN0ubc9u3Iche/ynzg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
