mt-pass: ENC[AES256_GCM,data:NErIQcG4uRT+hHQTC9S8ntZaqw0ci8q4yCY1Y/B0GcfwC8mZv6AuS9czjG8QKCAXcJs/bJu+4Ng5058f1hboeaIY6twB1aUyWh4IBsJ49h5yOAlaAdDtLkUslB2bILNzrzVCGHJeq8BGiw==,iv:z+nwQbZo/odEGy4XrAzAo9qXQx6XOEWSmMZGXV7n/kw=,tag:ymJZmYvzjLZkxNRKY4+3tA==,type:str]
zoho-pass: ENC[AES256_GCM,data:F4oPNzRyS7gyD9BK,iv:U7JPUuOwCA0HwkyBPCmI1ivxCMMyz8VVFP3YsNrJBrs=,tag:ur/9uXeX/40KOfV5lAh9jQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u4gjwdwevlzwfy94lvw69t32rueujk4evypc0r6fuq0nvmua94esge30uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6V2JEaXM2ek1SU21Kamt5
            K2V5N0xaY0hnbG1ja01HQitUYzIxWDgvR2c0CjR6bFhBdVAwNm1zc3k2VFBmTUpz
            Yi81TXZPMm9ZTFN1aVpoV0kzTG1iS3cKLS0tIGdFZlQvWVB5VmJlbXFUUFZldFd2
            TEY1WUhhdG5XSFpQL3FOb3lxRm9ETlEKUYoU+dFJuF/aOQPZtVHqlHO9JGQs2K2I
            SN5qlwUUZfEOwiM5ZYISzGibEAPm862Z2A4SLzgKBLI1KpoXQXDBYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T08:24:57Z"
    mac: ENC[AES256_GCM,data:LQhgWy7NBoryhzUrWmNPBV2SzTsV1dPCLhOBBWNc6pvnLjS0FPvO3EVXrD0yPjGmGZcxHea7lqVpYxqfxtPTMzLwEtA/dt+83bjbLaxS/9tBv5xttctwKBUFJeWGQxI0uETMlTo2mHh6JVz7sWM/FjO4jmNTjyDg0qQ4Ln43TPA=,iv:1s8qBvKBbR5zwoxooagEoAyguzSrwsoCoVimTlks2xc=,tag:NQIp2Ewtmz7ml+H1IDygOw==,type:str]
    pgp:
        - created_at: "2023-07-26T06:55:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hMIDn615Jx19RhwSBCMEAVTDLPidhQKtjruiJut23QOwaYsSzVLEPppg156w+UQn
            r8yGyckCaj5DhzsQrmnXxjXNp2PzltBxmBROKeYUDbKbAXUkJ1wF6+My/UCj8y97
            vPb7p2GmMNH/J8nzwmsYT4+1dUBmu/6rl8loukPW0h+1+ugYrNqYd69piDGxYPsc
            7D3ZMFsYnwWAEXUZXmYBhbclAbwpyXI0JwD539c0rMRu2WMRmLpgnen2NjdYX5h7
            WI93LdJeAbMjYyLOERngl+/jKWWA/2z4TkTHnr2AMvW2pKbk8n6X91Emyr5XI2rJ
            vkHinxCwDmaC+eUbGW4035WZ3g090fHKibMiTVOck4rmGA3UiXqI4zulYTjmXwYv
            o39Q+A==
            =iosj
            -----END PGP MESSAGE-----
          fp: F01B47BAD5FC895EE1F1B9E59FAD79271D7D461C
    unencrypted_suffix: _unencrypted
    version: 3.7.3
